In [1]:
number=15

In [2]:
type(number)

int

In [3]:
dir(number) # Bu kadar kaynak tüketimine gerek yok

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [4]:
my_list = [1,2,3]

In [5]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

## Numpy 

In [9]:
import numpy as np #Numpy'ın bize sunduğu önemli şeylerden biri Arrayler.

In [10]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [11]:
array_a = np.array([1,2,3,4])

In [12]:
array_b = np.array([0, 0.5, 1, 1.5, 2])

In [13]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
array_a[0] # Listelerdeki gibi indexler üzerinden erişiliyor.

1

In [16]:
array_b[-1]

2.0

In [17]:
array_a[:2]

array([1, 2])

In [18]:
array_a.dtype

dtype('int32')

In [19]:
array_a.dtype

dtype('int32')

In [20]:
array_b.dtype

dtype('float64')

In [22]:
empty_array = np.array([])

In [23]:
empty_array.dtype

dtype('float64')

In [24]:
np.array([1, 2, 3, 4], dtype=np.float_)

array([1., 2., 3., 4.])

In [25]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [26]:
array_c = np.array(["ada", "lovelace"])

In [27]:
array_c.dtype

dtype('<U8')

### Dimensions and Shapes

In [28]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [29]:
array_a.shape

(4,)

In [31]:
my_array.shape # 2 satırı var 3 sütunu var

(2, 3)

In [32]:
array_a.ndim

1

In [33]:
my_array.ndim

2

In [34]:
my_array.size

6

In [36]:
my_array = np.array([
    [
        [12, 11, 10],
        [9 ,8 ,7]
    ],
    [
        [6 ,5, 6],
        [3 ,2 ,1]
    ]
])

In [37]:
my_array.ndim

3

In [38]:
my_array.shape

(2, 2, 3)

In [39]:
my_array.size

12

### Indexing and Slicing

In [41]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [42]:
my_array[1]

array([4, 5, 6])

In [43]:
my_array[1] [0]

4

In [44]:
my_array[1, 0]

4

In [45]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
my_array[:2 , :2]

array([[1, 2],
       [4, 5]])

In [47]:
my_array[1] = np.array([10, 10, 10])

In [48]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [49]:
my_array[2] = 99

In [50]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [51]:
np.arange(1, 10 ,2)

array([1, 3, 5, 7, 9])

In [54]:
my_array= np.arange(0, 10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
my_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
np.arange(0, 10.1, 2)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [58]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [61]:
np.ones((2, 5, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [64]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
my_array = np.random.random((5,2))

In [66]:
my_array

array([[0.58489567, 0.96638545],
       [0.3703561 , 0.70118969],
       [0.56538811, 0.27919815],
       [0.58191501, 0.11568083],
       [0.31205358, 0.84087759]])

In [68]:
np.random.randint(100, size=(5,5))

array([[14, 52, 26, 58, 91],
       [58, 52, 97, 32, 53],
       [39, 17, 48, 64, 21],
       [79, 50, 59, 22, 57],
       [87, 34, 17, 28, 69]])

In [70]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [71]:
my_array.any()

True

In [72]:
my_array.all()

True

In [78]:
deneme = np.arange(0,10)
np.full(3, 2)

array([2, 2, 2])

In [79]:
np.concatenate([deneme, my_array])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

### Statistics

In [82]:
array1 = np.arange(0,10)
array1 = array1.reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
array1.sum()

45

In [84]:
array1.mean()

4.5

In [85]:
array1.std()

2.8722813232690143

In [86]:
array1.var()

8.25

In [87]:
array1.sum(axis=1)

array([10, 35])

In [88]:
array1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [89]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
array1 +=10
array1

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### Boolean Arrays

In [94]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [95]:
a[0], a[-1]

(0, 3)

In [96]:
a[[0, -1]]

array([0, 3])

In [97]:
a[[True, False, False,True]]

array([0, 3])

In [98]:
a >= 2

array([False, False,  True,  True])

In [99]:
a[a >= 2]

array([2, 3])

In [100]:
a.mean()

1.5

In [102]:
a[a >a.mean()]

array([2, 3])

In [103]:
a[~(a >a.mean())]

array([0, 1])

In [104]:
a[(a==0)|(a==1)]

array([0, 1])

In [105]:
a[(a<=2) & (a % 2==0 )]

array([0, 2])

In [115]:
example = np.random.randint(100,size=(3,3))
example

array([[72, 84, 55],
       [45, 19, 19],
       [93, 20, 53]])

In [116]:
bool_array = example > 30

In [117]:
bool_array

array([[ True,  True,  True],
       [ True, False, False],
       [ True, False,  True]])

In [118]:
example[bool_array]

array([72, 84, 55, 45, 93, 53])

In [126]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
array_1 = my_array.reshape(2,5)
array_2 = my_array.reshape(2,5)


In [127]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [128]:
np.dot(array_1, array_2)

ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

In [129]:
import sys

In [130]:
sys.getsizeof(10)

28

In [132]:
sys.getsizeof(1000**100)

160

In [133]:
np.dtype(int).itemsize

4

In [134]:
np.dtype(np.int8).itemsize

1

In [135]:
np.dtype(float).itemsize

8

In [138]:
sys.getsizeof ([1,2,3])

120

In [139]:
np.array([1, 2, 3]).nbytes

12

In [140]:
my_list = list(range(100000))

In [141]:
my_array = np.arange(100000)

In [142]:
%time np.sum(my_array ** 2)

CPU times: total: 0 ns
Wall time: 997 µs


216474736

In [143]:
%time sum([number ** 2 for number in my_list])

CPU times: total: 62.5 ms
Wall time: 56.8 ms


333328333350000